In [2]:
l = [1,1,2,3]

In [3]:
1

1

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [10]:
arr.dtype

dtype('int32')

In [11]:
array_new = np.array([1,2,3,4,5,6])

In [12]:
array_new + 3

array([4, 5, 6, 7, 8, 9])

In [13]:
type(array_new)

numpy.ndarray

In [14]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])

In [15]:
new_arr=my_numpy_array*3

In [16]:
new_arr

array([ 3,  6,  9, 12, 15])

In [17]:
type(my_numpy_array)

numpy.ndarray

In [18]:
l *3

[1, 1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3]

In [19]:
import numpy as np

my_array = np.array([1, 2, 3])
result = my_array * 2
print(result)  # Output: [2 4 6]
arr

[2 4 6]


array([1, 2, 3, 4])

In [20]:
arr>2

array([False, False,  True,  True])

In [ ]:
import seaborn as sns 
df = sns.load_dataset("titanic")
df.head()