### using functions to generate data

In [ ]:
import numpy as np

In [12]:
a33 = np.ones((3,4))

In [13]:
type(a33)

numpy.ndarray

In [14]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
import numpy as np

zeros_array = np.zeros((3,3))

In [9]:
ones_array = np.ones((2,4))

In [33]:
identity_matrix = np.eye(3)

In [11]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# specifying a data type

In [15]:
1==[3,4,4,5]

False

In [24]:
np.array(1,dtype=np.int64)

array(1, dtype=int64)

In [30]:
import numpy as np
int_array = np.array([1,2,3], dtype=np.int32)
float_array = np.array([0,1,2,3,3], dtype = np.float64)

In [34]:
#using a range ana linespace

a44 = np.arange(0,22)

In [35]:
a44

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [41]:
linespace_array_2 = np.linspace(0,10,6)
linespace_array_2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [42]:
scale_array = np.linspace(0,25,10)
scale_array

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [43]:
zeros_array = np.zeros((3,3))                #creating a 3x3 array  filled with 0s
ones_array = np.ones((2,4))                   #creating a 2x4 array  filled with 1s
identity_matrix = np.eye(3)                   #creating a 3x3 identity_matrix

identity_matrix = np.random.rand(4,4)       #creating a 4x4 array with random values in [0,1]


In [44]:

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
   ### basic indexing



In [48]:
import numpy as np
#1D
arr = np.array([13,56,25,688,])
print(arr[3])
print(arr[-2])               #accesing throuh last element

688
25


In [62]:
#2D

matrix = np.array([[1,2,3],
                   [4,5,6]])
print(matrix[0,1])
print(matrix[1,2])
print(matrix[0,2])

2
6
3


# ## 1D array slicing


In [61]:
import numpy as np

arr = np.array([25,50,80,90,30,60,69,])
print(arr[0:4])
print(arr[4:])
print(arr[::])
print(arr[:-2])

[25 50 80 90]
[30 60 69]
[25 50 80 90 30 60 69]
[25 50 80 90 30]


# 2D slicing

In [ ]:
    0 1 2 3
0  [2 6 4 5]
1  [3 65 7 6]
3  [5 8 2 4]

In [67]:
matrix = np.array([[2,4,4,5],
                  [3,65,7,6],
                  [5,8,2,4]])
print(matrix[0:2, 1:3])
print(matrix[0:3, 1:4])
print(matrix[1:2])

[[ 4  4]
 [65  7]]
[[ 4  4  5]
 [65  7  6]
 [ 8  2  4]]
[[ 3 65  7  6]]


In [3]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

## random 

In [5]:
import numpy as np
normal = np.random.rand(3,3)
print("normal distribution")


normal distribution


In [6]:
# Normal distribution
normal = np.random.randn(3, 3)
print("\n📈 Normal distribution:\n", normal)


📈 Normal distribution:
 [[-0.47932613 -0.04897076  1.14295717]
 [-0.71954837  0.42475556 -0.05140731]
 [ 0.91297389  1.28259901 -1.95730801]]


## np.where

In [ ]:
import numpy as np

In [13]:
arr = np.array([1,2,3,4,5])
np.where(arr>2)

(array([2, 3, 4], dtype=int64),)

## np.argmax()  np.argmin() -- index of max and min

In [11]:
arr = np.array([1,2,3,4,5])
np.argmin(arr)


0

In [12]:
np.argmin(arr)

0

## np.searchsorted() -- finds insertion index in a sorted array

In [ ]:
sorted_arr = np.array([1,3,5,7])

In [ ]:
print("Transposed:\n", np.transpose(matrix))


## mean caluculation

In [ ]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
print("mean value:",np.mean(arr))

mean value: 3.0


In [9]:
np.searchsorted(arr,6)

5

# 26 may 2025

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [31]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.array([[7,8],[4,8]])
np.concatenate((arr1,arr2,arr3),axis=1)

array([[1, 2, 5, 6, 7, 8],
       [3, 4, 7, 8, 4, 8]])

## vstack



In [25]:
arr3 = np.array([1,2,3])     ## stacks array vertically(row-wise)
arr4 = np.array([4,5,6])
np.vstack((arr3,arr4))

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr3 = np.array([1,2,3])     ## stacks array vertically(row-wise)
arr4 = np.array([4,5,6])
arr5 = np.array([7,8,9])
np.vstack((arr3,arr4,arr5))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## horizontal stack

In [32]:
a = np.array([1,2])
b = np.array([3,4])
np.hstack((a,b))

array([1, 2, 3, 4])

In [11]:
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6,6,7,8,9,10])
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [14]:
name = np.array([89, 478])
names  = np.array([48, 58])
np.hstack((name,names ))

array([ 89, 478,  48,  58])

### filtering array in numpy
#### filtering is a process of extracting only a 

In [53]:
### basic ex
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
arr<3
mask = arr<3

In [54]:
mask 

array([ True,  True, False, False, False, False, False])

In [55]:
arr[mask]   #true values <3

array([1, 2])

In [56]:
mask = arr>3

In [58]:
arr[mask]    # true values > 3

array([4, 5, 6, 7])

#### basic filtering example

In [59]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
mask = arr>3
filtered = arr[mask]
print("filtered elements(greater than 3):", filtered)

filtered elements(greater than 3): [4 5 6]


#### filtering a multplle conditions

### elements greater than 2 AND less than 6

In [71]:
import numpy as np

In [72]:
arr = np.array([1,2,3,4,5,6,7,8,9])
(arr > 3) & (arr < 9)        

array([False, False, False,  True,  True,  True,  True,  True, False])

In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9])
(arr > 0) & (arr < 10)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [77]:
(arr <= 3) | (arr > 8)

array([ True,  True,  True, False, False, False, False, False,  True])

##### filtering 2D array

In [79]:
matrix = np.array([
    [10,11,12],
    [13,14,15]
]) 
# get elements greater than 13
print("values > 13:",matrix[matrix > 13])

values > 13: [14 15]


In [81]:
matrix = np.array([
    [10,11,12],
    [13,14,15],
    [354,57,68]
]) 
# get elements greater than 13
print("values > 15:",matrix[matrix > 15])

values > 15: [354  57  68]


In [82]:
matrix = np.array([
    [10,11,12],
    [13,14,15],
    [354,57,68]
]) 
# get elements greater than 13
print("values < 15:",matrix[matrix < 15])

values < 15: [10 11 12 13 14]


####  case example :filtering exam scores

In [89]:
## use case example :filtering exam scores

scores = np.array([ 85,92,78,88,95,72,89,94,68,90])
print("values > 90:", scores[scores>90])

values > 90: [92 95 94]


In [109]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
# filter and print only even numbers
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [110]:
arr [arr % 3 ==0]

array([ 3,  6,  9, 12, 15])

In [112]:
arr[arr%2==1]  # odd num

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [113]:
arr [arr / 3 ==0]

array([], dtype=int32)

In [123]:
## print all tempetarure above 24
## print tempetarure between 20 and 24
## print tempetarure between 20 and 26

tempetarure = np.array([22.5,19.0,25.6,21.4,29.9,18.6,23.1,27.0])
print(tempetarure[tempetarure >=24])

[25.6 29.9 27. ]


In [21]:
import numpy as np

In [29]:
import numpy as np
tempetarure = np.array([22.5,19.0,25.6,21.4,29.9,18.6,23.1,27.0])
print("Temperature above 24:", tempetarure[tempetarure> 24])
print("Temperature between 20 and 26:",tempetarure [(tempetarure > 20) & (tempetarure < 26)])

Temperature above 24: [25.6 29.9 27. ]
Temperature between 20 and 26: [22.5 25.6 21.4 23.1]


In [35]:
## given a array of product price , filter the ones above 500 

price =np.array([250,499, 520,310,800,999,450,720])
print(" the price greater than 500:",price >= 500)

 the price greater than 500: [False False  True False  True  True False  True]


In [39]:

price = np.array([250,499, 520,310,800,999,450,720])
print(" the price greater than 500:",price[price >= 500])

 the price greater than 500: [520 800 999 720]
